-- Add down migration script here
DROP TABLE IF EXISTS TestScores;
DROP TABLE IF EXISTS Scores;
DROP TABLE IF EXISTS Limits;
DROP TABLE IF EXISTS Tests;
DROP TABLE IF EXISTS Submissions;
DROP TABLE IF EXISTS Tasks;
DROP TABLE IF EXISTS Competitions;
DROP TABLE IF EXISTS Users;
